"""add backlinks table

Revision ID: 1183625fe59a
Revises: d7282a933801
Create Date: 2026-05-29 19:08:20.463980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1183625fe59a'
down_revision: Union[str, Sequence[str], None] = 'd7282a933801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('anchor_text', sa.String(length=512), nullable=True),
    sa.Column('toxic_score', sa.Integer(), nullable=True),
    sa.Column('toxic_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backlinks')
    # ### end Alembic commands ###
