"""add llm_settings table

Revision ID: 1c36cf764fa9
Revises: 37e17d00997e
Create Date: 2026-05-29 18:27:52.618620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c36cf764fa9'
down_revision: Union[str, Sequence[str], None] = '37e17d00997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('ollama_url', sa.String(length=512), nullable=True),
    sa.Column('ollama_model', sa.String(length=128), nullable=True),
    sa.Column('openrouter_api_key', sa.String(length=256), nullable=True),
    sa.Column('openrouter_model', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_settings')
    # ### end Alembic commands ###
