"""add site_audits.pages_crawled

Revision ID: d7282a933801
Revises: 1c36cf764fa9
Create Date: 2026-05-29 19:04:03.129217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7282a933801'
down_revision: Union[str, Sequence[str], None] = '1c36cf764fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_audits', sa.Column('pages_crawled', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_audits', 'pages_crawled')
    # ### end Alembic commands ###
